/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "hzkzdqtdowxqtueqcjju"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6a3pkcXRkb3d4cXR1ZXFjamp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1MzA0OTQsImV4cCI6MjA3NzEwNjQ5NH0.T0ca3ElSxXIsqyyArlX5GjgPNMeCP-Zfe2qdaSqAl-k"